- semantics-3.0/Semantics4.hs
- Expand arguments names: c -> contract, sta -> state, mon -> money etc.
- Reduce code density by avoiding functions defined by patterns
- Rename `State` `account` and `choice` fields to `accounts` and `choices` respectively
> Small changes to (hopefully) prettify Semantics

- isabelle/ROOT
- isabelle/Semantics.thy
- src/Language/Marlowe/Analysis/FSSemantics.hs
- src/Language/Marlowe/Analysis/FSSemanticsFastVerbose.hs
- src/Language/Marlowe/Semantics.hs
Add Cond construct (If for values) to Marlowe semantics, static analysis, and Isabelle semantics, in order to reduce forking.
> SCP 285 - Add Cond construct (If for values)

- flake.nix
- isabelle/Cheatsheet.thy
- isabelle/ROOT
- isabelle/Specification.thy
- isabelle/document/root.tex
This PR adds the ability to generate a PDF from Isabelle and a Cheatsheet on how to control the generated documentation.
You can generate the documentation just by running 
```bash
[nix-develop] $ build-marlowe-proofs
```
The generated PDF is included in the PR for simplicity.
[document.pdf](https://github.com/input-output-hk/marlowe/files/9078023/document.pdf)
> SCP-4130 Create PDF from isabelle

- docs/challenge.md
- docs/tutorial-v3.0/actus-marlowe.adoc
- docs/tutorial-v3.0/escrow-ex.adoc
- docs/tutorial-v3.0/marlowe-data.adoc
- docs/tutorial-v3.0/marlowe-model.adoc
- docs/tutorial-v3.0/marlowe-plutus.adoc
- docs/tutorial-v3.0/marlowe-step-by-step.adoc
- docs/tutorial-v3.0/using-marlowe.adoc
- docs/workshop.md
- isabelle/Core/MoneyPreservation.thy
- isabelle/Core/Semantics.thy
- isabelle/Core/SemanticsTypes.thy
- isabelle/Core/SingleInputTransactions.thy
- isabelle/Core/Timeout.thy
- isabelle/Core/TransactionBound.thy
- isabelle/Core/ValidState.thy
- isabelle/Doc/Specification/Core.thy
- isabelle/StaticAnalysis/StaticAnalysis.thy
- src/Language/Marlowe/ACTUS/ActusContracts.hs
- src/Language/Marlowe/Analysis/FSSemanticsFastVerbose.hs
- src/Language/Marlowe/Examples/Auction.hs
- src/Language/Marlowe/Examples/Escrow.hs
- src/Language/Marlowe/Examples/Rent.hs
- src/Language/Marlowe/FindInputs.hs
- src/Language/Marlowe/Semantics.hs
- src/Language/Marlowe/Semantics/Deserialisation.hs
- src/Language/Marlowe/Semantics/Serialisation.hs
- src/Language/Marlowe/Semantics/Types.hs
- src/Main.hs
- using-marlowe.md
This PR modifies code and documentation to use POSIXTime instead of slot numbers. Essentially just a renaming because internally it has always been integers. But also some rephrasing in the documentation
> SCP-4242 - Update Slot to POSIXTime

- isabelle/Doc/Specification/Core.thy
- isabelle/Doc/Specification/Guarantees.thy
- isabelle/Doc/Specification/Specification.thy
Pre-audit draft of Marlowe specification. See [the attached PDF rendering](https://github.com/input-output-hk/marlowe/files/9330519/specification-v3.pdf).
There are several unsatisfactory aspects to the current draft: most of these relate to the fact that Isabelle's text-formatting system is designed for literate programming and apparently not for creating specification documents that excerpt definitions and proofs from other theory files. Specifically,
1. There is no antiquotation for record types.
2. There is no antiquotation for type synonym definitions.
3. Type synonyms are erased in `datatype` antiquotations.
4. Apparently, the Isabelle definitions of functions cannot be excerpted. (The present document falls back on Haskell code generation for this, but that is clearly …
> SCP-4320 SCP-4321 SCP-4322 Isabelle specifications for Core Marlowe

- isabelle/Core/Semantics.thy
Adds lemmas about division suggested by reviews of the text spec document
```
Lemmas around division? maybe extend the following to proof evalValue and not just div:
* divMultiply <- already done as `evalDivMultiplyFractByConstant`
* divAbsMultiply
Lemmas should be
* (i) exact multiples divide with no remainder,
* (ii) the remainder equals the excess above an exact multiple
* (iii) negation commutues with division
```
> SCP-4380 - Extend division proofs

- isabelle/Doc/Specification/Core.thy
I added test to clarify which warnings are appropriate for implicit and explicit payments of zero.
> SCP-4269 Clarified warnings for zero payments

- isabelle/Core/SemanticsTypes.thy
- isabelle/Doc/Specification/Core.thy
- isabelle/Doc/Specification/Specification.thy
- src/Language/Marlowe/Semantics/Deserialisation.hs
- src/Language/Marlowe/Semantics/Serialisation.hs
- src/Language/Marlowe/Semantics/Types.hs
The PubKey hash Party constructor doesn't allow for staking keys, it is easier to use an opaque Address, which each blockchain can use with different schemas.
> SCP-4388 Replace PK for Address

- isabelle/CodeExports/CodeExports.thy
- isabelle/Core/OptBoundTimeInterval.thy
- isabelle/Core/Semantics.thy
- isabelle/Core/TimeRange.thy
- isabelle/Doc/Specification/document/root.tex
- isabelle/ROOT
- isabelle/generated/Arith.hs
- isabelle/generated/OptBoundTimeInterval.hs
- isabelle/generated/SList.hs
- isabelle/generated/Semantics.hs
This PR writes a function in the Isabelle specification to calculate bounds for time intervals given a contract and a concrete time.
When submitting a transaction it needs to have a time interval that fits the contract remaining, otherwise the semantics will issue a `TEAmbiguousTimeIntervalError` error. Calculating a suitable interval is non-trivial. This function makes an effort at maximising an interval while avoiding TEAmbiguousTimeIntervalError errors.
The type of the function `calculateTimeInterval` is `Maybe Integer -> POSIXTime -> Contract -> (Maybe POSIXTime, Maybe POSIXTime)` where the `Integer` would be the number of inputs to consider (where `Nothing` means an arbitrary number), the first `POSIXTime` would be a point in the interval (typically the current time), the `Contract` …
> SCP-4526 - Write function to calculate bounds for time intervals given a contract

- isabelle/Core/SemanticsTypes.thy
- isabelle/Doc/Specification/Core.thy
- isabelle/Doc/Specification/Guarantees.thy
- isabelle/Doc/Specification/document/root.tex
This PR removes some FIXME and TODOs from the 
[specification-v3.pdf](https://github.com/input-output-hk/marlowe/files/10144052/specification-v3.pdf)
> Tidy up specification document

- isabelle/CodeExports/CodeExports.thy
- isabelle/generated/List.hs
- isabelle/generated/MList.hs
- isabelle/generated/PositiveAccounts.hs
- isabelle/generated/SemanticsGuarantees.hs
- isabelle/marlowe.cabal
- marlowe-spec-test/src/Marlowe/Spec/Core/Arbitrary.hs
- marlowe-spec-test/src/Marlowe/Spec/Core/Serialization/Json.hs
- marlowe-spec-test/src/Marlowe/Spec/Interpret.hs
- marlowe-spec-test/src/Marlowe/Spec/LocalInterpret.hs
- marlowe-spec-test/src/Marlowe/Spec/TypeId.hs
This PR adds `Gen`/`GenT` instances for all the types covered in the serialization specification, inspired by the [Arbitrary instances from marlowe-cardano](https://github.com/input-output-hk/marlowe-cardano/blob/main/marlowe-test/src/Spec/Marlowe/Semantics/Arbitrary.hs), and the corresponding roundtrip test.
> SCP-4698 - Implement roundtrip test for all serialized types

- flake.nix
The `edit-marlowe-proofs` fails when executing for the first time with the following error:
```
/nix/store/rpb1r5dpkw6rknm6gmvqqpa710lqhakj-isabelle-2021-1/Isabelle2021-1/src/Tools/jEdit/jedit_base/plugin.scala:7: error: package isabelle contains object and package with same name: Doc
one of them needs to be removed from classpath
package isabelle.jedit_base
^
1 error
Failed to compile Scala sources
```
by entering the directory the script works just fine.
> Fix edit-marlowe-proofs script

- isabelle/LICENSE
- isabelle/marlowe.cabal
- marlowe-spec-test/LICENSE
- marlowe-spec-test/marlowe-spec-test.cabal
The cabal packages `marlowe` and `marlowe-test-spec` violated cabal requirements:
1. Files outside of the folder with the `.cabal` file were references, causing the resulting source `.tar` file to be invalid.
2. The `marlowe` package name repeats the package of the same name in `marlowe-cardano`, which violates the requirement that package names be globally unique.
Both of these problems are remedied here:
Question to reviewers: *Is `marlowe-isabelle` the best choice for the package name, or should it be something like `marlowe-reference`?*
> SCP-4748 Fixed cabal packages

- isabelle/haskell/MarloweCoreJson.lhs
- marlowe-spec-test/README.md
- marlowe-spec-test/marlowe-spec-test.cabal
- marlowe-spec-test/src/Marlowe/Spec/Core.hs
- marlowe-spec-test/src/Marlowe/Spec/Core/Arbitrary.hs
- marlowe-spec-test/src/Marlowe/Spec/Core/Semantics.hs
- marlowe-spec-test/src/Marlowe/Spec/Core/Serialization/Json.hs
- marlowe-spec-test/src/Marlowe/Spec/Interpret.hs
- marlowe-spec-test/src/Marlowe/Spec/LocalInterpret.hs
- marlowe-spec-test/src/Marlowe/Spec/Reproducible.hs
- marlowe-spec-test/src/Marlowe/Utils.hs
This PR adds the new command `EvalValue` to the spec test. It basically generates random `Value`s see what the Isabelle specification thinks the result should be and compares it with the actual response of spec client.
By doing this feature a bug was found in the purescript-marlowe repository, for which rounding of `(DivValue (NegValue (Constant 2)) (Constant 20))` differs. In the specification the value is evaluated to `0` and in purescript-marlowe to `-1`.
> SCP-4901 - Add eval value test

- isabelle/Core/Semantics.thy
- isabelle/Doc/Specification/Core.thy
- marlowe-spec-test/src/Marlowe/Spec/Core/Arbitrary.hs
- marlowe-spec-test/src/Marlowe/Spec/Core/Semantics.hs
This PR adds a lemma that proves that if the numerator is lower than the denominator (in absolute), then `DivValue` rounds to `0`.
> SCP-4869 - Add lemma and test around rounding to zero

- isabelle/CodeExports/CodeExports.thy
- isabelle/Doc/Specification/Examples.thy
- isabelle/Doc/Specification/Specification.thy
- isabelle/Doc/Specification/document/root.tex
- isabelle/Examples/Escrow.thy
- isabelle/ROOT
- isabelle/generated/Examples/Escrow.hs
- isabelle/marlowe.cabal
- marlowe-spec-test/marlowe-spec-test.cabal
- marlowe-spec-test/src/Marlowe/Spec/Core/Examples.hs
- marlowe-spec-test/src/Marlowe/Spec/Core/Examples/Escrow.hs
This PR adds 
- the Escrow example to Isabelle
- and the generated specification
- Unit tests for all possible outcomes of the contract to the test-spec
> SCP-4908: Add the Escrow to the examples suite

- marlowe-spec-test/src/Marlowe/Spec/Core/Semantics.hs
- marlowe-spec-test/src/Marlowe/Spec/Interpret.hs
- marlowe-spec-test/src/Marlowe/Spec/LocalInterpret.hs
The PR introduces `EvalObservation` to the test spec protocol.
> PLT-4250: `evalObservation` in spec-test

- CHANGELOG.md
- isabelle/Core/OptBoundTimeInterval.thy
- isabelle/Core/PositiveAccounts.thy
- isabelle/Core/QuiescentResult.thy
- isabelle/Core/Semantics.thy
- isabelle/Core/SemanticsGuarantees.thy
- isabelle/Core/SemanticsTypes.thy
- isabelle/Core/SingleInputTransactions.thy
- isabelle/Core/TimeRange.thy
- isabelle/Core/Timeout.thy
- isabelle/Core/ValidState.thy
- isabelle/Doc/Specification/Core.thy
- isabelle/Doc/Specification/Guarantees.thy
- isabelle/generated/Semantics.hs
TODO: This is marked as a draft until PR 161 has been merged.
This PR adds a changelog starting from the audit and addresses several small findings of the first milestone report.
> PLT-3505 small fixes to the isabelle specification

- CHANGELOG.md
- isabelle/Doc/Specification/document/root.tex
This PR just modifies the changelog and date of the PDF in order to make the second release candidate.
I've attached the candidate PDF: [specification-v3-rc2.pdf](https://github.com/input-output-hk/marlowe/files/11442580/specification-v3-rc2.pdf)
> Marlowe v3 RC2

- README.md
Changed `marlowe-finance.io` to `marlowe.iohk.io`.
> Updated URLs to point to new Marlowe website.
